name: rojo
 
on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: model
          type: rbxm

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: Spectre
          path: ./Spectre.rbxm