name: rojo
 
on:
  push:
    branches: [master]

jobs:
  checkout:
    name: Checkout repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  rojo:
    needs: checkout
    name: Build with Rojo
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        needs:
        with:
          output: model
          type: rbxm
  
  artifact:
      needs: rojo
      name: Upload artifact
      runs-on: ubuntu-latest
      steps:
      - uses: actions/upload-artifact@v4.0.0
        with:
          name: Spectre
          path: ${{ github.workspace }}/Spectre.rbxm